@omdbApiUrl = https://www.omdbapi.com/?apikey={{omdbApiKey}}

@searchOmdbUrl = {{omdbApiUrl}}&s=
@mediaOmdbUrl = {{omdbApiUrl}}&i=

@baseUrl = http://localhost:3000
@omdbBaseUrl = http://localhost:3000/omdb

@searchUrl = {{omdbBaseUrl}}/media?s=
@idUrl = {{omdbBaseUrl}}/media/

{{searchUrl}}love

###

# @name search
{{searchOmdbUrl}}love

###

{{idUrl}}{{search.response.body.Search.0.imdbID}}

###


{{mediaOmdbUrl}}{{search.response.body.Search.1.imdbID}}

###

POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "email": "stan@stan.com",
  "username": "stanislas",
  "password": "S3CR37p455!"
}

###
{{baseUrl}}/users

###
{{baseUrl}}/users/1

### 
POST {{baseUrl}}/movies
Content-Type: application/json

{
  "imdbID": "tt1570728"
}


### 
GET {{baseUrl}}/movies

### 
GET {{baseUrl}}/movies/1

### 
GET {{baseUrl}}/labels

### 
POST {{baseUrl}}/labels
Content-Type: application/json

{
  "name": "science fiction"
}

###
POST {{baseUrl}}/movies/1/labels
Content-Type: application/json

{
  "name": "science fiction"
}

###
DELETE {{baseUrl}}/movies/1/labels/1


### 
GET {{baseUrl}}/labels?q=science
