version: '3.1'

services:
  db:
    image: postgres:16.2-bullseye
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      DB_USER: stan
      DB_PASS: stan
      DB_NAME: media
      SHADOW_DB_NAME: shadow_media
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data/pgdata
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8080:8080'
